### ISSUE TITLE
websocket agent 调用dispose会卡住

### ISSUE THREAD

**Issue by fewpiwork** [int2e/HPSocket.Net#10]
![image](https://user-images.githubusercontent.com/32926982/104272316-d1d48600-54d7-11eb-93b8-0665eb6e98eb.png)

**Comment by fewpiwork** [comment]
5.7.3.2 版本

**Comment by int2e** [comment]
提供下您的demo

**Comment by SIXGODLI** [comment]
请问如何使用HttpEasyClient里面的SendWsMessage，有例子吗

**Comment by int2e** [comment]
> 请问如何使用HttpEasyClient里面的SendWsMessage，有例子吗

没有的
