### ISSUE TITLE
UDPClient  随机端口号可以正常连接，但通过 BindPort 绑定本地端口号，无法正常连接！why？

### ISSUE THREAD

**Issue by dapeng17951** [int2e/HPSocket.Net#11]
UDPClient  随机端口号可以正常连接，但通过 BindPort 绑定本地端口号，无法正常连接！why？

**Comment by int2e** [comment]
已修复，nuget包稍候上传beta版，请关注最新beta版本。

**Comment by dapeng17951** [comment]
感谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "int2e"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 下午3:01
收件人: "int2e/HPSocket.Net"<HPSocket.Net@noreply.github.com&gt;; 
抄送: "风停了"<327632904@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [int2e/HPSocket.Net] UDPClient  随机端口号可以正常连接，但通过 BindPort 绑定本地端口号，无法正常连接！why？ (#11)





 
已修复，nuget包稍候上传beta版，请关注最新beta版本。
