### ISSUE TITLE
请问如何使用HttpEasyClient里面的SendWsMessage，有例子吗

### ISSUE THREAD

**Issue by SIXGODLI** [int2e/HPSocket.Net#13]
求个demo

**Comment by SIXGODLI** [comment]
``        public void 给标签页发送消息_异步(string 消息)
        {
            byte[] data = System.Text.Encoding.UTF8.GetBytes(消息);
            //string str = System.Text.Encoding.UTF8.GetString(data);
            //Console.WriteLine("给标签页发送消息_异步:\n" + str);

            var state = new HPSocket.WebSocket.MessageState();
            state.Final = true;
            state.BodyLength =ulong.Parse(data.Length.ToString());
            HPSocket.WebSocket.OpCode opCode = HPSocket.WebSocket.OpCode.Close ;
            HPSocket.WebSocket.Rsv r = HPSocket.WebSocket.Rsv.Compression;
            state.Rsv = r;
            state.OpCode = opCode;
            _log(data.Length.ToString());
            http.SendWsMessage(state, data,data.Length);
            
        }

**Comment by SIXGODLI** [comment]
发送之后http服务器会关闭

**Comment by int2e** [comment]
你确认升级为ws协议了没有

**Comment by int2e** [comment]
长时间无反馈
