### ISSUE TITLE
在CentOS7中OnClose事件和在Window系统中不一样

### ISSUE THREAD

**Issue by z514987467** [int2e/HPSocket.Net#14]
开发框架：.NET CORE3.1
问题描述：
在Win10开发环境中，使用IClient连接服务失败会回调OnClose事件，但是在Docker下Centos7环境中不会回调

**Comment by int2e** [comment]
能否提供能重现问题的demo

**Comment by z514987467** [comment]
简单写了个Demo：https://github.com/z514987467/HPSocketTest.git
’‘’
 private HandleResult TcpClient_OnClose(IClient sender, SocketOperation socketOperation, int errorCode)
        {
            logger.LogDebug($"TcpClient_OnClose#socketOperation:{socketOperation}");
            return HandleResult.Ok;
        }
‘’‘
如果程序在启动的时候，SockerServer不可用，Window平台会执行这个方法，CentOS7下不执行

**Comment by int2e** [comment]
收到,测试好了告诉你结果

**Comment by ldcsaa** [comment]
要检查start返回值。为true时才可能触发。

**Comment by int2e** [comment]
> 简单写了个Demo：https://github.com/z514987467/HPSocketTest.git
> private HandleResult TcpClient_OnClose(IClient sender, SocketOperation socketOperation, int errorCode)
> {
> logger.LogDebug($"TcpClient_OnClose#socketOperation:{socketOperation}");
> return HandleResult.Ok;
> }
> 如果程序在启动的时候，SockerServer不可用，Window平台会执行这个方法，CentOS7下不执行

linux上必须判断connect的返回值,为true才会触发onclose,平台差异.你自己处理下

**Comment by z514987467** [comment]
好，谢谢
