### ISSUE TITLE
断开连接触发的OnMessage事件，如果直接返回HandleResult.Ok会有延迟

### ISSUE THREAD

**Issue by wphubs** [int2e/HPSocket.Net#16]
大佬好，想请教个问题

断开连接时触发的OnMessage事件，如果不发送数据，会延迟5秒才断开连接，如果发送数据，则会立即断开。

这个是有什么说法吗？是必须要发送一个消息到客户端吗

DEMO的WebSocketServer-TestEcho可以复现这个问题

    public HandleResult OnMessage(IWebSocketServer sender, IntPtr connId, bool final, OpCode opCode, byte[] mask, byte[] data)
        {
            Console.WriteLine($"OnMessage({connId}), final: {final}, op code: {opCode}, data length: {data.Length}");

            //这里注释，不发送数据
            //var ok = sender.Text(connId, $"这里只是一个欢迎页面, 只是欢迎您, 您可以连接到 {(sender.IsSecure ? "wss" : "ws")}://{sender.Uri.Host}:{sender.Uri.Port}/echo");
            //return ok ? HandleResult.Ok : HandleResult.Error;

            return HandleResult.Ok;

        }

**Comment by wphubs** [comment]
我们客户端是uniapp项目，IOS断开连接时即使在OnMessage发送数据，也会有5秒左右延迟， 但是安卓是正常的。
我将这个问题反馈给uniapp官方时，他们给我提供了一个其他的websocket测试地址，实际测试是正常没有延迟。 
请问我这面需要针对IOS系统做什么单独的处理吗。。

**Comment by int2e** [comment]
ws的消息机制是断开连接实际上是发个断开包...
如果想要断开连接应该发送断开的msg包而不是用error ,  error会立即断开tcp连接,也可以用
但是理论上是要告诉对方你要关闭连接了, 发close消息

**Comment by wphubs** [comment]
用工具测试正常，怀疑uniapp和HP-Socket有兼容性的问题，目前不在客户端关闭了， 改成服务端踢出客户端了。
