### ISSUE TITLE
_agent.GetConnectionState(connId) result 6422588

### ISSUE THREAD

**Issue by yj-zhang** [int2e/HPSocket.Net#18]
When I use TcpPullAgent, call GetConnectionState() Back 6422588

code show as below:
`LogHelper.WriteLog($"{_agent.GetConnectionState(connId).ToString()}   connId = {connId}");`

The print information is as follows:
6422588   connId = 1

Normally should show:
Connected   connId = 1

Looking forward to your answer，thank you

**Comment by int2e** [comment]
能提供一个可重现的demo吗

**Comment by yj-zhang** [comment]
很高兴收到您的回复。demo我写好后发给您！最近两天没有出现6422588这个值，但是通信一段时间后连接状态会从Connected变为Connecting，并且暂时看来是不会变回Connected，一直是Connecting。不过这个状态下是可以正常发送数据的。-------- 原始邮件 --------发件人： int2e ***@***.***>日期： 2021年6月29日周二 半夜11:07收件人： "int2e/HPSocket.Net" ***@***.***>抄送： yj-zhang ***@***.***>, Author ***@***.***>主    题： Re: [int2e/HPSocket.Net] _agent.GetConnectionState(connId) result 6422588 (#18)

能提供一个可重现的demo吗

**Comment by int2e** [comment]
能提供个重现的demo我才好测试

**Comment by yj-zhang** [comment]
嗯嗯，这周太忙了，没有来得及写，我争取这几天写一下请您看一下！-------- 原始邮件 --------发件人： int2e ***@***.***>日期： 2021年7月4日周日 晚上9:10收件人： "int2e/HPSocket.Net" ***@***.***>抄送： yj-zhang ***@***.***>, Author ***@***.***>主    题： Re: [int2e/HPSocket.Net] _agent.GetConnectionState(connId) result 6422588 (#18)

能提供个重现的demo我才好测试

**Comment by yj-zhang** [comment]
你好！我写了一个demo，可以复现问题。
[demo链接](https://github.com/yj-zhang/TestHPSocket.git)
项目中附带了几张截图和一个文档，里面记录了一些问题！

**Comment by int2e** [comment]
ok 我现在看看

**Comment by int2e** [comment]
已经找到问题了, 是因为设置了连接超时时间, 定时器的回调函数中有个指针释放位置不正确的bug导致的这个问题, 稍后我马上发布新的nuget包, 请更新到最新版本.


> 另外
6、_agent.Connect("127.0.0.1", 5555, out connId)，这种调用方法有可能出现调用返回后connId还没有分配地址的情况吗（分配的时间比返回时间晚）？项目中出现过这条语句后紧接着使用connId变量导致报错：空引用异常；但是报错在vs中查看时connId却不是空引用了；
7、问一个问题，使用您这个库时输出目录会自动附带上HPSOCKET4C.dll吗？我创建了两个项目一个会自动附带一个不会自动附带，是有哪里进行设置吗？
8、HPSOCKET4C.dll如何改变在输出目录的引用位置，只能和执行文件在同级目录吗？我想放到指定目录，但是尝试环境变量和指定privatePath都不行；

`
6: 这个不会, 如果能用稍后的最新版本复现才能查出问题, 否则我怀疑跟定时器是同个问题, 再观察下吧.
`

`
7: nuget包是会附带dll到输出目录的, 如果你是在core或者.net5运行程序没有问题, 确看不到dll, 应该是在exe的runtimes\win-x64 或 runtimes\win-x86 目录下, 这个.net core / .net 5 与.net framework是不同的, 可以自行查资料, 当然如果runtimes\* 目录下没有 ,放exe目录也是可以的
`
`
8: 实际上你不用动源码, .net core或.net5项目参考 [项目exe].deps.json的配置, 网上查资料, .net framework的项目只要你的dll在系统或当前用户的环境变量目录或者exe目录均可以被找到
`

**Comment by yj-zhang** [comment]
很高兴收到您的回复！我明天更新下库版本。关于HPSOCKET4C.dll库存放位置的问题：我现在的项目会自动附带这个HOSOCKET4C.dll和HPSocket.Net.dll到输出目录。现在可以将HPSocket.Net.dll放到通过环境变量指定的目录，但是HPSOCKET4C.dll只能放在和EXE同样的目录下，放到其他的目录运行程序会报找不到dll，即使是在环境变量指定的目录也找不到。项目是在.net framework下的，改变dll存放位置目的是整理存放软件执行文件的目录。期待您的解答！-------- 原始邮件 --------发件人： int2e ***@***.***>日期： 2021年7月8日周四 中午12:55收件人： "int2e/HPSocket.Net" ***@***.***>抄送： yj-zhang ***@***.***>, Author ***@***.***>主    题： Re: [int2e/HPSocket.Net] _agent.GetConnectionState(connId) result 6422588 (#18)
已经找到问题了, 是因为设置了连接超时时间, 定时器的回调函数中有个指针释放位置不正确的bug导致的这个问题, 稍后我马上发布新的nuget包, 请更新到最新版本.

另外
6、_agent.Connect("127.0.0.1", 5555, out connId)，这种调用方法有可能出现调用返回后connId还没有分配地址的情况吗（分配的时间比返回时间晚）？项目中出现过这条语句后紧接着使用connId变量导致报错：空引用异常；但是报错在vs中查看时connId却不是空引用了；
7、问一个问题，使用您这个库时输出目录会自动附带上HPSOCKET4C.dll吗？我创建了两个项目一个会自动附带一个不会自动附带，是有哪里进行设置吗？
8、HPSOCKET4C.dll如何改变在输出目录的引用位置，只能和执行文件在同级目录吗？我想放到指定目录，但是尝试环境变量和指定privatePath都不行；

6: 这个不会, 如果能用稍后的最新版本复现才能查出问题, 否则我怀疑跟定时器是同个问题, 再观察下吧.
7: nuget包是会附带dll到输出目录的, 如果你是在core或者.net5运行程序没有问题, 确看不到dll, 应该是在exe的runtimes\win-x64 或 runtimes\win-x86 目录下, 这个.net core / .net 5 与.net framework是不同的, 可以自行查资料, 当然如果runtimes\* 目录下没有 ,放exe目录也是可以的
8: 实际上你不用动源码, .net core或.net5项目参考 [项目exe].deps.json的配置, 网上查资料, .net framework的项目只要你的dll在系统或当前用户的环境变量目录或者exe目录均可以被找到

**Comment by int2e** [comment]
如果你有dll目录的疑问,可以加我的qq,我给你远程看一下. 
qq:1013706666
