### ISSUE TITLE
In .net5 enabled "PublishSingleFile" result in build fail

### ISSUE THREAD

**Issue by Jie2GG** [int2e/HPSocket.Net#20]
I am in my project import HP-Socket.Net after, useing visual studio publish singe file application, resule displaying build fail.

The logs:
```
1>“GenerateBundle”任务意外失败。
1>System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath
1>   在 Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs)
1>   在 Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore()
1>   在 Microsoft.NET.Build.Tasks.TaskBase.Execute()
1>   在 Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute()
1>   在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>   在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== 生成: 成功 0 个，失败 0 个，最新 8 个，跳过 0 个 ==========
========== 发布: 成功 0 个，失败 1 个，跳过 0 个 ==========
```

I create demo project for this purpose, recurrence the problem.
Demo: [Test.zip](https://github.com/int2e/HPSocket.Net/files/7064492/Test.zip)

**Comment by int2e** [comment]
等微软解决....

**Comment by int2e** [comment]
还有一个临时解决方案, 就是你用源码, 别用nuget包, 发布单文件之后, 把hpsocket4c.dll或者so拷贝到程序目录 
现在的问题是hpsocket4c.dll或者so不能被打包进单文件, 这是微软需要解决的问题

**Comment by int2e** [comment]
> @int2e 我觉得这个问题现阶段是可以解决的. 因为微软的 WebView2 也是采用相同的办法进行打包的. 并不会出现上述日志的问题. 具体的问题我还在研究

如果研究明白了,麻烦告诉我一声,我也想知道怎么解决的...
:)
