### ISSUE TITLE
Error message: Core dumped

### ISSUE THREAD

**Issue by tracymcgradyzwc** [int2e/HPSocket.Net#21]
发布到linux上面，一直报 （段错误）

write(2, "  -> [01] /root/MyWork/remotely/"..., 122  -> [01] /root/publish/libhpsocket4c.so : (HP_TcpServer_SetSocketBufferSize+0x43) [0x7f8b52ff1dd3]
) = 122
write(2, "  -> [02] [0x7f8addebcb48]\n", 27  -> [02] [0x7f8addebcb48]
) = 27
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5598a3c4487e} ---
rt_sigprocmask(SIG_UNBLOCK, [RT_2], NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [SEGV], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [RT_2], NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f8b58a56630}, NULL, 8) = 0
unlink("/tmp/clr-debug-pipe-122880-287755908-in") = 0
unlink("/tmp/clr-debug-pipe-122880-287755908-out") = 0
unlink("/tmp/dotnet-diagnostic-122880-287755908-socket") = 0
rt_sigreturn({mask=[PIPE]})             = 69920
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5598a3c4487e} ---
+++ killed by SIGSEGV (core dumped) +++
段错误

不知道怎么来解决这个问题。。希望能得到帮助。  谢谢。

**Comment by ldcsaa** [comment]
信息不够详细
