### ISSUE TITLE
error on  private readonly ITcpServer _server = new TcpServer();

### ISSUE THREAD

**Issue by mzelecom** [int2e/HPSocket.Net#23]
hi .
I get this error on line ( private readonly ITcpServer _server = new TcpServer();)

`
An unhandled exception of type 'System.DllNotFoundException' occurred in HPSocket.Net.dll

Additional information: Unable to load DLL 'hpsocket4c': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
`

**Comment by int2e** [comment]
nuget package?

是中国人话加qq 1013706666 我帮你看看

**Comment by mzelecom** [comment]
my nuget is 
dotnet add package HPSocket.Net --version 5.8.5.2
Do you have a telegram?

**Comment by int2e** [comment]
telegram @AMaleCat
