### ISSUE TITLE
你好，我的程序使用HttpsEasyAgent类会出现内存溢出，是我的调用方式有问题吗

### ISSUE THREAD

**Issue by alittieBird** [int2e/HPSocket.Net#24]
![image](https://user-images.githubusercontent.com/18206927/162871165-3960759f-3d9f-42c4-8704-e1ddcb7c2dc2.png)

![image](https://user-images.githubusercontent.com/18206927/162870966-533cd1a5-6374-4722-99ba-e7d933c02572.png)
大概运行2个小时左右就会出现out of memory的异常

**Comment by int2e** [comment]
只有这一点代码我无法判断
