### ISSUE TITLE
unity中使用HPSocket.Net  il2cpp打包遇上的问题 

### ISSUE THREAD

**Issue by lovehou922** [int2e/HPSocket.Net#29]
unity中使用HPSocket.Net (C# 版) 导入HPSocket4C.dll
使用il2cpp打包 win64平台，运行导出的exe 报错
![20230423-161643](https://user-images.githubusercontent.com/13890768/233828516-f353f8b6-e892-4899-a2ce-7f75d485c544.jpg)

**Comment by int2e** [comment]
unity不支持原生dll打包？ 改用.net自带的socket，或者完全使用c#写的socket库吧。
