### ISSUE TITLE
When WebSocket uses SSL, the client cannot connect properly

### ISSUE THREAD

**Issue by z171262221** [int2e/HPSocket.Net#30]
I used WebSocket and did it according to WebSocketServer TestEcho. I wanted to provide a secure SSL connection, so I added the configuration items for the relevant certificates, as follows:

string url = "wss://0.0.0.0:16099";
IWebSocketServer Server = = new WebSocketServer(url);

Server.SslConfiguration = new SslConfiguration
{
	FromMemory = false,
	VerifyMode = SslVerifyMode.Peer,
	//CaPemCertFileOrPath = "root.pem",
	PemCertFile = "ssl-cert\\eylin.cn.cer",
	PemKeyFile = "ssl-cert\\eylin.cn.key",
	//KeyPassword = "123456",
};

Then I used WebSocketClient_TestEcho To connect "wss://test70.eylin.cn:16099"

When set to:
agent.SslConfiguration = new SslConfiguration
{
	FromMemory = false,
	VerifyMode = SslVerifyMode.None,
};
That is, without verifying the server certificate, it can connect and work correctly.

When set to:
agent.SslConfiguration = new SslConfiguration
{
	FromMemory = false,
	VerifyMode = SslVerifyMode.Peer,
};
That is, when verifying the server certificate, it cannot connect normally!
Then I tested on the webpage, Flutter, and other places but couldn't connect properly. I don't know why?

I can ensure that my certificate is correct because I built a WebSocket provided by SuperSocket using eylin.cn.jks and its password, which can work properly anywhere.

**Comment by int2e** [comment]
VERIFY_PEER should be a mutual authentication process. I can't resolve this issue, and I'm not sure if you have solved it. If not, you might want to ask @ldcsaa
