### ISSUE TITLE
"The HPSocket.net library throws an error when running on Raspberry Pi OS Lite 64bit ARM64 environment."

### ISSUE THREAD

**Issue by blackshowp** [int2e/HPSocket.Net#31]
"When running the HPSocket.net library on Raspberry Pi OS Lite 64bit ARM64 environment, the following error is encountered: 'Unable to load shared library 'hpsocket4c' or one of its dependencies. To assist in diagnosing loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable.' Specific errors include:

/app/hpsocket4c.so: cannot open shared object file: No such file or directory.

/usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/libhpsocket4c.so).

libhpsocket4c.so: cannot open shared object file: No such file or directory.

/app/hpsocket4c: cannot open shared object file: No such file or directory.

/app/libhpsocket4c: cannot open shared object file: No such file or directory.

How should this be resolved?"

**Comment by int2e** [comment]
You need to download the source code from `https://github.com/ldcsaa/HP-Socket` yourself and build the .so file in your OS.
