### ISSUE TITLE
关于 TcpPortForwarding 粘包问题

### ISSUE THREAD

**Issue by WongHouLeong** [int2e/HPSocket.Net#34]
我正在使用TcpPortForwarding来做数据转发和处理，因为我需在OnServerReceive中对数据进行分析和修改，TcpPortForwarding组件好像没接口添加Data Receive Adapter模型来处理粘包问题

**Comment by int2e** [comment]
对的, 确实没有, 他目前只是一个单纯的数据转发, 前2天更新了下, 现在支持你自己是否拦截某个包不转发, 也支持对数据做处理后在转发了, 但是他不支持数据接收适配器, 你可以自己扩展下~~
