### ISSUE TITLE
TcpPortForwarding 内存问题

### ISSUE THREAD

**Issue by WongHouLeong** [int2e/HPSocket.Net#35]
您好，同样在使用端口转发出现了一些问题想请教一下;
测试情况是服务端会不断向客户端发送数据，但客户端进程被暂停或者挂起，不会响应转发端

1.端口转发程序的内存会越来越大(一晚上几百MB)
2.按我的理解，数据转发时会发生握手失败，数据会不断堆积且尝试重发，但调用GetPendingDataLength长度为0
![1](https://github.com/user-attachments/assets/2b67b7da-1326-4abd-bd7f-4b0023da49f1)
3.调用send应该会失败,但返回成功了
![2](https://github.com/user-attachments/assets/5f51aab3-29c1-46fb-a83a-c7601165148b)

请问组件是否有便捷的办法处理客户端无回应的问题? 非常感谢!

**Comment by ldcsaa** [comment]
数据已经发到网卡的缓存区，不会算入HP的pendingdata

**Comment by int2e** [comment]
你这种情况没有什么好办法的, 尤其是本机测试 -_-!
