### ISSUE TITLE
事件绑定 OnSend 无法监听

### ISSUE THREAD

**Issue by zhoumiCode** [int2e/HPSocket.Net#37]
使用场景 WIN10 X64
使用例子 HPSocket.Net demo
TcpAgent-TestEcho
TcpServer-TestEcho

在`TcpAgent-TestEcho中`仅添加事件绑定
```
_agent.OnSend += OnSend;
```
和

```
private HandleResult OnSend(IAgent sender, IntPtr connId, byte[] data)
  {
      AddLog($"OnSend({connId}), ({data.Length} bytes)");

      return HandleResult.Ok;
  }
```

无法成功监听 OnSend
其他六个监听事件正常

![image](https://github.com/user-attachments/assets/b674b999-89e1-4af6-83cb-43d78c93a247)

hp-socket version: 6.0.2_1

**Comment by int2e** [comment]
已修复, 更新6.0.3版本即可
