### ISSUE TITLE
“System.BadImageFormatException”类型的未经处理的异常在 HPSocket.Net.dll 中发生 

### ISSUE THREAD

**Issue by dapeng17951** [int2e/HPSocket.Net#4]
“System.BadImageFormatException”类型的未经处理的异常在 HPSocket.Net.dll 中发生 

其他信息: 试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)

x86,.net framework 4.0,hapsocket.net 5.72

![image](https://user-images.githubusercontent.com/39858062/88901717-bbb56f00-d283-11ea-8f7a-b87da3f9b626.png)

**Comment by dapeng17951** [comment]
补充：win10系统，编译无问题，运行报错；x86,.net framework 4.0,hapsocket.net 5.72，win10

**Comment by dapeng17951** [comment]
Nuget包引用错乱啦，已解决

**Comment by int2e** [comment]
这个一般都是 x86引用了64位dll 或者64位引用了x86的dll导致的，要明确指定项目是x86还是64的。解决就好。

**Comment by stevenweis** [comment]
請問一下我目前也遇到相同問題, 因為元件的關係 平台目標一定要在x86, 請問是否有x86的 HPSocket.Net.dll

**Comment by dapeng17951** [comment]
活动解决方案平台，目标平台，配置检查一下呗。可以先把这两项固定好了x86，再nuget引入hpsocket.net。hpsocket.net 已做适配吧，c++的x86 HPSocket4C.dll可以在nuget下载处的runtime中找到。
