### ISSUE TITLE
用docker做成images后无法启动

### ISSUE THREAD

**Issue by z514987467** [int2e/HPSocket.Net#5]
用docker做成images后，启动报错
```
An assembly specified in the application dependencies manifest (WebApi.deps.json) was not found:
  package: 'HPSocket.Net', version: '5.7.2'
  path: 'runtimes/linux-x64/native/libhpsocket4c.so'
```
是不是.NET CORE平台开发的，在linux平台下的Docker打镜像不行，我用windows平台下的Docker打镜像可以

**Comment by z514987467** [comment]
可以发布成独立文件，但是我现在想发布到linux平台，在用Docker打包成images后，启动报错

**Comment by z514987467** [comment]
我试了生成单个文件也是这个错误

**Comment by int2e** [comment]
确定 runtimes/linux-x64/native/libhpsocket4c.so 这个文件存在吗，非独立的时候

**Comment by z514987467** [comment]
> 确定 runtimes/linux-x64/native/libhpsocket4c.so 这个文件存在吗，非独立的时候

之前是我打成独立文件有点问题，现在打包成独立文件，选择linux-x64平台，没问题不报错误了，

**Comment by int2e** [comment]
ok，恭喜
