### ISSUE TITLE
一个程序开启两个不同端口的TcpServer，其中一个会shutdown。

### ISSUE THREAD

**Issue by wphubs** [int2e/HPSocket.Net#7]
ITcpServer<byte[]> server = new TcpServer<byte[]>
            {
                Address = 127.0.0.1,
                Port = 8888,
                DataReceiveAdapter = new HeadTailDataReceiveAdapter(),
            };
            server.OnPrepareListen += OnPrepareListen;
            server.OnAccept += OnAccept;
            server.OnParseRequestBody += OnParseRequestBody;
            server.OnClose += OnClose;
            server.OnShutdown += OnShutDown;
            server.Start();

----------------------------------------------------------
1、可以正常开启，在接收几条数据后，其中一个Server就会触发shutdown事件，看不到错误信息。 如果只开启一个Server就没问题。
2、客户端连接不同的Server端口，所有客户端ConnId是顺序下来的。这个ConnId生成规则是什么呀，有影响吗。

麻烦大佬指点一下，谢谢！

**Comment by int2e** [comment]
1.需要你提供demo
2.每个独立的server的生成顺序都是从1开始到32或64位int的最大无符号值，然后继续从1开始。

**Comment by w405287435** [comment]
[Demo.zip](https://github.com/int2e/HPSocket.Net/files/5375008/Demo.zip)
 
@int2e  你好，这个是DEMO。开启一个Server，两个Client可以复现，不到一分钟会出现shutdown，谢谢。

**Comment by int2e** [comment]
`
        public void InitSocketServer(string Address, ushort Port)
        {
             ITcpServer<byte[]>  server = new TcpServer<byte[]>
            {
                Address = Address,
                Port = Port,
                DataReceiveAdapter = new HeadTailDataReceiveAdapter(),
            };
            server.OnPrepareListen += OnPrepareListen;
            server.OnAccept += OnAccept;
            server.OnParseRequestBody += OnParseRequestBody;
            server.OnClose += OnClose;
            server.OnShutdown += OnShutDown;
            server.Start();
        }
`

改为 

`
 private ITcpServer<byte[]> server = null;
        public void InitSocketServer(string Address, ushort Port)
        {
            server = new TcpServer<byte[]>
            {
                Address = Address,
                Port = Port,
                DataReceiveAdapter = new HeadTailDataReceiveAdapter(),
            };
            server.OnPrepareListen += OnPrepareListen;
            server.OnAccept += OnAccept;
            server.OnParseRequestBody += OnParseRequestBody;
            server.OnClose += OnClose;
            server.OnShutdown += OnShutDown;
            server.Start();
        }
`

你的问题属于server被gc释放了，不是hpsocket的问题，写法问题，更正后就好了。

**Comment by int2e** [comment]
另外注意main函数里的调用，最好两个new的临时对象也改成static 变量 就绝对没有问题了。

**Comment by w405287435** [comment]
谢谢大佬指点，之前就是莫名其妙shutdwon，一直没找到原因，原来是GC的问题， 终于搞明白了，非常感谢
