### ISSUE TITLE
WebSocket配置SSL证书的问题

### ISSUE THREAD

**Issue by wphubs** [int2e/HPSocket.Net#9]
你好，想在server端配置wss，目前用的阿里云免费证书，可用类型有Tomcat、Apache 、Nginx、IIS、JKS，下载完之后没有.cer格式的证书，我应该下载使用哪个类型的证书呢，需要使用到nginx吗？ 谢谢

                       server.SslConfiguration = new SslConfiguration
                        {
                            // 不从内存加载证书
                            FromMemory = false,

                            // ssl证书配置, 支持单向验证
                            VerifyMode = SslVerifyMode.Peer,
                            CaPemCertFileOrPath = "ssl-cert\\ca.crt",
                            PemCertFile = "ssl-cert\\server.cer",
                            PemKeyFile = "ssl-cert\\server.key",
                            KeyPassword = "123456",
                        };

**Comment by wphubs** [comment]
目前用nginx实现了，不知到能不能直接配置wss？

**Comment by int2e** [comment]
nginx可以实现反向代理的方式实现wss，就是ws服务开起来，nginx通过https反向代理的方式代理到ws，即可实现nginx证书到wss了
